dataset: 
  train:
    dataset_path: /home/ubuntu/data
    part: train
  val:
    dataset_path: /home/ubuntu/data
    part: dev
    limit: 6400
  test:
    dataset_path: /home/ubuntu/data
    part: eval
training:
  batch_size: 32
  lr: 1.0e-4
  weight_decay: 1.0E-4
  num_epochs: 10
  epoch_size: null
  save_path: /home/ubuntu/anti_spoof/saved/{pretty_time}.pth
  ce_weights: '[1.0, 9.0]'
model:
  p_sinc:
    out_channels: 20
    kernel_size: 1024   # hint
  p_1res_block:
    channels: 20        # hint
    count: 2
  p_2res_block:
    channels: 128       # hint
    count: 4    
  p_gru:
    hidden_size: 1024
    num_layers: 6       # hint 
